### ISSUE TITLE
Not able to support a batch size of 512 on A100 nvidia GPU

### ISSUE THREAD

**Issue by EaswarGn** [sgrvinod/chess-transformers#15]
I am trying to training the CT-ED-45 model on an A100 nvidia gpu with 83gb ram and 53gb vram, but I keep getting resource errors when I set the batch size to 512. The gpu was only able to support a batch size of 128 because of the size of the model. What machine did you train these models on, what were the specs of these machines, and how did you manage such a large batch size?

**Comment by sgrvinod** [comment]
Hi, I trained it on a 2080ti on my personal PC with about 11-12GB of VRAM. My PC has 32GB of RAM. That model is relatively small and should not require that much RAM.

**Comment by sgrvinod** [comment]
Can you manually check the number of parameters in your model?

`sum([p.numel() for p in model.parameters()])`

It should be around 45 million.

**Comment by sgrvinod** [comment]
If you're still having issues, I can check tomorrow again that it works fine on my PC.

**Comment by EaswarGn** [comment]
Oh yeah, I forgot that I was using the same model configs from the CT-EFT-85 model in this model (CT-ED-45), so instead of 45mill params I have around 200mil params. Thanks
